version: '3.2'
services:
  nginx:
    container_name: vu-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
    - ./server:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "XDG_CONFIG_HOME=/app"
    ports:
    - "8080:80"
    links:
      - php-fpm
      # - node

  php-fpm:
    container_name: vu-php-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./server:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
    links:
      - mysql
      # - node

  php-cli:
    container_name: vu-php-cli
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
    - ./server:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "COMPOSER_MEMORY_LIMIT=-1"
    links:
      - mysql
    tty: true

  mysql:
    image: mysql:8.0
    container_name: vu-mysql
    volumes:
    - database:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=laravel"
    ports:
    - "33061:3306"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vu-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=secret
      - UPLOAD_LIMIT=64M
    restart: always
    ports:
      - 8081:80
  
  # node:
  #   image: node:18-alpine
  #   ports:
  #       - "3001:3000"
  #   volumes:
  #   - ./server:/var/www
  #   working_dir: /var/www
  #   tty: true

  # admin:
  #   container_name: vu-admin
  #   build:
  #     context: ./admin
  #     dockerfile: Dockerfile
  #   ports:
  #       - "3002:3000"
  #   volumes:
  #     - ./admin/app:/vu-admin/app

  # client:
  #   container_name: vu-client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #       - "3003:3000"
  #   volumes:
  #     - ./client/app:/vu-client/app
  #     - ./client/public:/vu-client/public

volumes:
  database: